// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc1qcU9Ie8fQVZYFcSmyhCL9vVIco7amE',
    appId: '1:542283688369:web:055ecb4ce7dd1ee09cf590',
    messagingSenderId: '542283688369',
    projectId: 'achieveagility-46b70',
    authDomain: 'achieveagility-46b70.firebaseapp.com',
    storageBucket: 'achieveagility-46b70.appspot.com',
    measurementId: 'G-J39YZ1PP3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuC-WgP4_R-NVIzkMVAvfhM_l_qhZy6K0',
    appId: '1:542283688369:android:8663949e106234ae9cf590',
    messagingSenderId: '542283688369',
    projectId: 'achieveagility-46b70',
    storageBucket: 'achieveagility-46b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8QISiK6NakUlvg0_7W2JQ8LvEiWOUAAE',
    appId: '1:542283688369:ios:6d7bc432c72792219cf590',
    messagingSenderId: '542283688369',
    projectId: 'achieveagility-46b70',
    storageBucket: 'achieveagility-46b70.appspot.com',
    iosClientId: '542283688369-32lno6bjl1bntdcn0kgs2flb9e9gflcg.apps.googleusercontent.com',
    iosBundleId: 'com.roasted.titleTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8QISiK6NakUlvg0_7W2JQ8LvEiWOUAAE',
    appId: '1:542283688369:ios:e56a221d7b9360279cf590',
    messagingSenderId: '542283688369',
    projectId: 'achieveagility-46b70',
    storageBucket: 'achieveagility-46b70.appspot.com',
    iosClientId: '542283688369-2q8r4jsf0fcjpqvilioc0oid3vrcmm5r.apps.googleusercontent.com',
    iosBundleId: 'com.roasted.titleTrackerApp.RunnerTests',
  );
}
